Update RepositoryInterface.php
I'm getting this error :
FatalErrorException: Compile Error: Can't inherit abstract function Countable::count() (previously declared abstract in Pagekit\Component\Package\Repository\RepositoryInterface) in E:\projects\pagekit\vendor\pagekit\framework\src\Component\Package\Repository\RepositoryInterface.php line 8

There is no need to declare "count" function when we are extending \Countable interface